apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kagent.fullname" . }}-getter-role
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
rules:
# Kagent's own custom resources - READ access for controller and handlers
- apiGroups:
  - kagent.dev
  resources:
  - agents
  - modelconfigs
  - teams
  - toolservers
  - memories
  verbs:
  - get
  - list
  - watch

# Status access for kagent resources
- apiGroups:
  - kagent.dev
  resources:
  - agents/status
  - modelconfigs/status
  - teams/status
  - toolservers/status
  - memories/status
  verbs:
  - get
  - patch
  - update

# Core resources - SPECIFIC resources only (used by tools container)
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - events
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch

# Pod logs access (used by tools container for troubleshooting)
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get

# Apps resources - SPECIFIC resources only (used by tools container)
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kagent.fullname" . }}-writer-role
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
rules:
# Kagent's own custom resources - ONLY what the controller manages
- apiGroups:
  - kagent.dev
  resources:
  - agents
  - modelconfigs
  - teams
  - toolservers
  - memories
  verbs:
  - create
  - update
  - patch
  - delete

# Status updates for kagent resources
- apiGroups:
  - kagent.dev
  resources:
  - agents/status
  - modelconfigs/status
  - teams/status
  - toolservers/status
  - memories/status
  verbs:
  - get
  - patch
  - update

# Finalizers for kagent resources
- apiGroups:
  - kagent.dev
  resources:
  - agents/finalizers
  - modelconfigs/finalizers
  - teams/finalizers
  - toolservers/finalizers
  - memories/finalizers
  verbs:
  - update

# Secrets - ONLY for API key management (used by HTTP handlers)
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch

# ConfigMaps - ONLY for memory storage (used by memory handlers)
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch

